# Generated by Django 5.0.6 on 2025-09-05 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionjob',
            name='annotated_image',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
