# Generated by Django 5.0.6 on 2025-09-05 19:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_detectionjob_annotated_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkDetectionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DONE', 'Done'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('excel_file', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('jobs', models.ManyToManyField(related_name='bulk_job', to='detections.detectionjob')),
            ],
        ),
    ]
